import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'

import { applicationModules } from '../src/modules/index.js'
import type { ModuleDefinition } from '../src/modules/module.js'

const outputPath = resolve(import.meta.dirname, '../../../docs/modules/README.md')
const lines = [
  '# Application module catalog',
  '',
  '> Generated by `pnpm modules:generate`. Do not edit this file by hand.',
  '',
  'The catalog is derived from the compile-time module descriptors used by the API composition root.',
  '',
]

for (const module of applicationModules as readonly ModuleDefinition[]) {
  lines.push(`## ${module.id}`, '')
  lines.push(`- HTTP: ${module.http.access} at \`${module.http.path}\``)
  lines.push(
    `- Dependencies: ${format(
      module.dependencies.map(({ moduleId, ports }) =>
        ports.length > 0 ? `${moduleId} (${ports.join(', ')})` : moduleId,
      ),
    )}`,
  )
  lines.push(`- Entities: ${format(module.entities.map((entity) => String(entity.name)))}`)
  lines.push(
    `- Public container registrations: ${format(Object.keys(module.registrations.public))}`,
  )
  lines.push(
    `- Private container registrations: ${format(Object.keys(module.registrations.private))}`,
  )
  lines.push(`- Published events: ${format(module.events.publishes.map((event) => event.id))}`)
  lines.push(
    `- Event subscriptions: ${format(module.events.subscribes.map((subscription) => subscription.event.id))}`,
  )
  lines.push(`- Extension points provided: ${format(module.extensions.provides)}`)
  lines.push(`- Extension points used: ${format(module.extensions.contributes)}`, '')

  if (module.capabilities.length > 0) {
    lines.push('| Capability | Requires | Description |', '| --- | --- | --- |')
    for (const capability of module.capabilities) {
      lines.push(
        `| ${format([capability.id])} | ${format(capability.requires ?? [])} | ${capability.description} |`,
      )
    }
    lines.push('')
  }

  lines.push('| Operation | Kind | Capability |', '| --- | --- | --- |')
  for (const operation of module.operations) {
    lines.push(
      `| ${format([operation.id])} | ${operation.kind} | ${operation.capability ? format([operation.capability]) : 'Public'} |`,
    )
  }
  lines.push('')
}

await mkdir(dirname(outputPath), { recursive: true })
await writeFile(outputPath, `${lines.join('\n').trimEnd()}\n`, 'utf8')
console.log(`Module catalog written to ${outputPath}`)

function format(values: readonly string[]) {
  return values.length > 0 ? values.map((value) => `\`${value}\``).join(', ') : 'None'
}
